#!/bin/bash

#
# See the file LICENSE for redistribution information.
#
# Copyright (c) 2011, 2022 Oracle and/or its affiliates.  All rights reserved.
#
# Fill in site-appropriate values for PATH, KVHOME, and CLASSPATH
# This script will be executed by the Oracle Database server.
# If you are using user-specified Formatters, by sure to include their home
# in the CLASSPATH.
#
export KVHOME=/usr/local/kv
export PATH=$KVHOME/exttab/bin:/usr/lib/jvm/java-1.8.0-openjdk/bin
export CLASSPATH="$KVHOME/lib/kvstore.jar:$KVHOME/examples"
java oracle.kv.exttab.Preproc $*
